version: "3.9"
services:
  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    depends_on: 
      - java_db  
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_PASSWORD: mariadb

